"""Configuration parameters for the pre-pump long strategy."""

# Thresholds for pre-pump detection
PRE_PUMP_SCORE_THRESHOLD = 3
BBW_PERCENTILE_THRESHOLD = 10
VOL_RATIO_60_MIN = 1.2
VOL_RATIO_60_MAX = 3.0
BODY_RATIO_ACCUM_MAX = 0.4
REL_STRENGTH_MIN = 0.0
BUY_RATIO_MIN = 0.6
FUNDING_NEAR_ZERO = 0.0002
OI_CHANGE_60_MIN = 0.05

# Entry trigger parameters
VOL_RATIO_30_ENTRY = 3.0
BODY_RATIO_ENTRY = 0.6
ATR_MULTIPLIER_ENTRY = 2.0

# Windows
BASE_WINDOW_MINUTES = 60

# Backtest parameters
INITIAL_BALANCE = 1000.0
RISK_PER_TRADE = 0.01
TAKE_PROFIT_MULTIPLIER = 3.0
STOP_LOSS_MULTIPLIER = 1.0
MAX_OPEN_TRADES = 5
MAX_HOLDING_MINUTES = 240
FEE_RATE = 0.0004
